# Generated by Django 4.0.3 on 2023-11-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatpost_convention_alter_chatpost_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='chatpost_id',
            new_name='chatpost',
        ),
        migrations.RenameField(
            model_name='chatpost',
            old_name='user_id',
            new_name='user',
        ),
    ]
